services:
  mongo:
    container_name: mongoDB
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      -  ./database:/data/db

  mongo-express:
    container_name: mongoExpress
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
