@startuml patientenJourny

start
:Patient betritt Arzt Praxis;

:Schalter: Name / Versichertenkarte abgeben;
if(Notfall) then(Nein)
:suche via kv
GET /Patient?identifier=KVNR (Name, usw. als Tiebreaker!));
else(ja)
 :suche ohne kv
 (via Name und anderen Attributen)
 GET /Patient?name=...&birthdate=...;
endif

if (gefunden?) then (ja)
else (nein)
  :Patient neu anlegen
  POST /Patient auf FHIR;
endif
:Wichtig;
 note right
    Patient existiert zu diesem Zeitpunk 100% auf fhir (Source of Truth)
  end note

:Anamnesebogen / Update ausfüllen
(inkl. Einwilligung zur Datenübermittlung);

:Aktiven Consent prüfen
GET /Consent?patient=...&status=active (FHIR);

if (neuer Consent angegeben?) then (ja)
  :Neuen Consent mit der Anamnese
  als Transaction Bundle senden;
else (nein)
  if (aktiver Permit-Consent vorhanden?) then (ja)
    :Anamnese mit bestehendem
    Consent übertragen;
  else (nein)
    :Keine klinischen Daten übertragen;
  endif
endif

:Wichtig;
 note right
   Wenn nichts neues dazukommt dann kann Anamnese 
   übersprungen werden) = Wir haben zu diesem 
   Zeitpunkt auch 100% die neuen Daten zum aktualiseren
  end note

if (Consent?) then (ja)
  :Aufnahme-Bundle zu FHIR?
  Vorher ziehen?
  Dauermedikation im System aktualisieren
  POST / (Bundle = transaction):
    Condition (Vorerkrankungen)
  + MedicationStatement (Dauermedikamente)
  + Consent (DSGVO)
  + Provenance
  -> Alle referenzieren den Patienten!;
else (nein)
  :Anamnese bleibt lokal / auf Papier
  Ablehnung Consent zu FHIR (bereits vorhanden)) für dokumentation
  keine klinischen Daten (Condition,
  MedicationStatement);
endif

:Behandlungszimmer beim Arzt;
note left
vieles hiervon ist nur "gespielt"
end note
:Arzt: Medikationshistorie abrufen
GET /MedicationStatement?subject=...&status=active;
note right
Dummy GET für unser Szenario
end note
:Arzt: Diagnose + Schmerzmedikation wählen;
note right
Es wird einfach random ausgewählt
end note

:Verordnung vormerken
(lokal in MongoDB);

if (Consent?) then (ja)
: Vorgang abschließen
POST / (Bundle transaction)
MedicationRequest + Provenance atomar;
else (nein)
:bleibt local bei uns
 Ablehnung Consent zu FHIR (bereits vorhanden)) für dokumentation;
end if

:Behandlungsdokumentation bleibt gespeichert (Aufbewahrungspflicht von 10 Jahre);
note right
Durch mongoDB geregelt (expireAfterSeconds)
end note

:Medikation erfolgreich verordnet;
stop
@enduml
